# Generated by Django 5.1.5 on 2025-01-19 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_path', models.URLField()),
                ('is_showing', models.BooleanField(db_index=True, default=True)),
                ('short_name', models.CharField(max_length=255)),
                ('cost', models.IntegerField(db_index=True)),
                ('city', models.CharField(db_index=True, max_length=255, null=True)),
                ('space', models.FloatField(db_index=True, null=True)),
                ('description', models.TextField(null=True)),
                ('conditions_accommodation', models.TextField(null=True)),
                ('contacts', models.TextField(null=True)),
                ('finding_description', models.TextField(null=True)),
                ('helpful_info', models.TextField(null=True)),
                ('parking_info', models.TextField(null=True)),
                ('banner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.banner')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.category')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.typeobject')),
            ],
        ),
    ]
