# Generated by Django 5.1.5 on 2025-01-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='url_path',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
