# Generated by Django 5.1.5 on 2025-04-04 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0002_objectsmediafile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectsmediafile',
            name='file',
            field=models.FileField(upload_to='objects/', verbose_name='Файл'),
        ),
    ]
