# Generated by Django 5.1.5 on 2025-01-24 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0002_alter_object_url_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.object')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.service')),
            ],
        ),
        migrations.AddField(
            model_name='object',
            name='services',
            field=models.ManyToManyField(through='objects.ObjectServices', to='objects.service'),
        ),
    ]
