# Generated by Django 5.1.5 on 2025-04-04 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0003_alter_objectsmediafile_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objectsmediafile',
            old_name='article',
            new_name='object',
        ),
    ]
