# Generated by Django 5.1.5 on 2025-03-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0004_inventory_objectinventory_object_inventories'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='near_metro',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
