# Generated by Django 5.1.5 on 2025-01-26 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0004_inventory_objectinventory_object_inventories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['name'], 'verbose_name': 'Баннер', 'verbose_name_plural': 'Баннеры'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['name'], 'verbose_name': 'Инвентарь', 'verbose_name_plural': 'Инвентарь'},
        ),
        migrations.AlterModelOptions(
            name='object',
            options={'verbose_name': 'Объект', 'verbose_name_plural': 'Объекты'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['name'], 'verbose_name': 'Регион', 'verbose_name_plural': 'Регионы'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name'], 'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterModelOptions(
            name='typeobject',
            options={'ordering': ['name'], 'verbose_name': 'Тип объекта', 'verbose_name_plural': 'Типы объектов'},
        ),
        migrations.AlterField(
            model_name='object',
            name='banner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.banner'),
        ),
        migrations.AlterField(
            model_name='object',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.category'),
        ),
        migrations.AlterField(
            model_name='object',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='conditions_accommodation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='contacts',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='finding_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='helpful_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='parking_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='space',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.typeobject'),
        ),
        migrations.AlterModelTable(
            name='banner',
            table='banners',
        ),
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='inventory',
            table='inventories',
        ),
        migrations.AlterModelTable(
            name='object',
            table='objects',
        ),
        migrations.AlterModelTable(
            name='region',
            table='regions',
        ),
        migrations.AlterModelTable(
            name='service',
            table='services',
        ),
        migrations.AlterModelTable(
            name='typeobject',
            table='types',
        ),
    ]
