# Generated by Django 5.1.5 on 2025-04-09 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0004_rename_article_objectsmediafile_object'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='url_path',
        ),
        migrations.RemoveField(
            model_name='object',
            name='near_metro',
        ),
        migrations.CreateModel(
            name='NearMetroObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.metro')),
                ('object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.object')),
            ],
        ),
        migrations.AddField(
            model_name='object',
            name='near_metro',
            field=models.ManyToManyField(db_index=True, null=True, through='objects.NearMetroObject', to='objects.metro'),
        ),
    ]
