# Generated by Django 5.1.5 on 2025-01-26 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0005_alter_banner_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Баннер'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Инвентарь'),
        ),
        migrations.AlterField(
            model_name='object',
            name='banner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.banner', verbose_name='Баннер'),
        ),
        migrations.AlterField(
            model_name='object',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='object',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='object',
            name='conditions_accommodation',
            field=models.TextField(blank=True, null=True, verbose_name='Условия заселения'),
        ),
        migrations.AlterField(
            model_name='object',
            name='contacts',
            field=models.TextField(blank=True, null=True, verbose_name='Контактные данные'),
        ),
        migrations.AlterField(
            model_name='object',
            name='cost',
            field=models.IntegerField(db_index=True, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='object',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='object',
            name='finding_description',
            field=models.TextField(blank=True, null=True, verbose_name='Как найти'),
        ),
        migrations.AlterField(
            model_name='object',
            name='helpful_info',
            field=models.TextField(blank=True, null=True, verbose_name='Полезная информация'),
        ),
        migrations.AlterField(
            model_name='object',
            name='is_showing',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Опубликовать?'),
        ),
        migrations.AlterField(
            model_name='object',
            name='parking_info',
            field=models.TextField(blank=True, null=True, verbose_name='Информация по парковке'),
        ),
        migrations.AlterField(
            model_name='object',
            name='short_name',
            field=models.CharField(max_length=255, verbose_name='Короткое имя'),
        ),
        migrations.AlterField(
            model_name='object',
            name='space',
            field=models.FloatField(blank=True, db_index=True, null=True, verbose_name='Площадь'),
        ),
        migrations.AlterField(
            model_name='object',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.typeobject', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='object',
            name='url_path',
            field=models.CharField(max_length=255, unique=True, verbose_name='Маршрут'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Услуги'),
        ),
        migrations.AlterField(
            model_name='typeobject',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Тип объекта'),
        ),
    ]
