# Generated by Django 5.1.5 on 2025-04-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0005_remove_object_url_path_remove_object_near_metro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='sleeps',
            field=models.CharField(max_length=255, null=True, verbose_name='Количество спальных мест'),
        ),
    ]
