# Generated by Django 5.1.5 on 2025-04-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0006_object_sleeps'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='capacity',
            field=models.IntegerField(null=True, verbose_name='Количество людей'),
        ),
    ]
