# Generated by Django 5.1.5 on 2025-01-26 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0006_alter_banner_name_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objectinventory',
            options={'ordering': ['object', 'inventory'], 'verbose_name': 'Инвентарь для объекта', 'verbose_name_plural': 'Инвентарь для объекта'},
        ),
        migrations.AlterModelOptions(
            name='objectservices',
            options={'ordering': ['service', 'object'], 'verbose_name': 'Услуга для объекта', 'verbose_name_plural': 'Услуги для объекта'},
        ),
    ]
