# Generated by Django 5.1.5 on 2025-04-12 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0007_object_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_to_show',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Услуга отб.на сайте'),
        ),
        migrations.AlterField(
            model_name='objectsmediafile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='objects/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='objectsmediafile',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_media', to='objects.object'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Идентификатор услуги'),
        ),
        migrations.CreateModel(
            name='UrlObjectMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL изображения')),
                ('is_external', models.BooleanField(default=True, verbose_name='Внешний ресурс')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='url_media', to='objects.object')),
            ],
        ),
    ]
