# Generated by Django 5.1.5 on 2025-01-26 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0007_alter_objectinventory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectinventory',
            name='amount',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='objectinventory',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.inventory', verbose_name='Наименование инвентаря'),
        ),
        migrations.AlterField(
            model_name='objectinventory',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.object', verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='objectservices',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.object', verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='objectservices',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.service', verbose_name='Услуга'),
        ),
    ]
