# Generated by Django 5.1.5 on 2025-04-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0008_service_icon_service_title_to_show_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='object',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
