# Generated by Django 5.1.5 on 2025-01-26 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0008_alter_objectinventory_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='amount_rooms',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Количество комнат'),
        ),
        migrations.AddField(
            model_name='object',
            name='floor',
            field=models.IntegerField(db_index=True, default=1, null=True, verbose_name='Этаж'),
        ),
        migrations.AddField(
            model_name='object',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.region', verbose_name='Регион'),
        ),
    ]
