# Generated by Django 5.1.5 on 2025-05-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0009_object_latitude_object_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='amount_sleeps',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Количество спальных мест'),
        ),
        migrations.AlterField(
            model_name='object',
            name='sleeps',
            field=models.CharField(max_length=255, null=True, verbose_name='Количество спальных мест (описание)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='object_icons/', verbose_name='Иконка'),
        ),
    ]
