# Generated by Django 5.1.5 on 2025-08-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0009_object_latitude_object_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='icon/', verbose_name='Иконка'),
        ),
    ]
