# Generated by Django 5.1.5 on 2025-08-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0010_alter_service_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='objects/icons', verbose_name='Иконка'),
        ),
    ]
