# Generated by Django 5.1.5 on 2025-05-26 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0010_object_amount_sleeps_alter_object_sleeps_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessibility',
            fields=[
                ('accessibility_type', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ViewFromWindow',
            fields=[
                ('notation_view', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='object',
            name='view_from_window',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.viewfromwindow'),
        ),
    ]
