# Generated by Django 5.1.5 on 2025-01-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0010_metro_object_address_metronearobject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='near_metros',
            field=models.ManyToManyField(db_index=True, through='objects.MetroNearObject', to='objects.metro'),
        ),
    ]
