# Generated by Django 5.1.5 on 2025-05-26 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0011_accessibility_viewfromwindow_object_view_from_window'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bathroom',
            fields=[
                ('bathroom_type', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='object',
            name='bathroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.bathroom'),
        ),
    ]
