# Generated by Django 5.1.5 on 2025-08-06 17:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0012_alter_service_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='conditions_accommodation',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Условия заселения'),
        ),
        migrations.AlterField(
            model_name='object',
            name='contacts',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Контактные данные'),
        ),
        migrations.AlterField(
            model_name='object',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='object',
            name='finding_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Как найти'),
        ),
        migrations.AlterField(
            model_name='object',
            name='helpful_info',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Полезная информация'),
        ),
        migrations.AlterField(
            model_name='object',
            name='parking_info',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Информация по парковке'),
        ),
    ]
