# Generated by Django 5.1.5 on 2025-06-03 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0012_bathroom_object_bathroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessibility',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accessibility',
            name='accessibility_type',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='near_metro',
            field=models.ManyToManyField(db_index=True, through='objects.NearMetroObject', to='objects.metro'),
        ),
        migrations.CreateModel(
            name='ObjectAccessibilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessibility_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='objects.accessibility')),
                ('object_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='objects.object')),
            ],
        ),
        migrations.AddField(
            model_name='object',
            name='accessibility',
            field=models.ManyToManyField(through='objects.ObjectAccessibilities', to='objects.accessibility'),
        ),
    ]
