# Generated by Django 5.1.5 on 2025-08-10 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0013_alter_object_conditions_accommodation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessibility_type', models.CharField(db_index=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bathroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bathroom_type', models.CharField(db_index=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ViewFromWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notation_view', models.CharField(db_index=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='object',
            name='bathroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.bathroom'),
        ),
        migrations.CreateModel(
            name='ObjectAccessibilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessibility_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='objects.accessibility')),
                ('object_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='objects.object')),
            ],
        ),
        migrations.AddField(
            model_name='object',
            name='accessibility',
            field=models.ManyToManyField(through='objects.ObjectAccessibilities', to='objects.accessibility'),
        ),
        migrations.AddField(
            model_name='object',
            name='view_from_window',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.viewfromwindow'),
        ),
    ]
