# Generated by Django 5.1.5 on 2025-06-20 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0013_accessibility_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('price', models.IntegerField(db_index=True)),
                ('is_available', models.BooleanField(default=True)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_prices', to='objects.object')),
            ],
            options={
                'unique_together': {('object', 'date')},
            },
        ),
    ]
