# Generated by Django 5.1.5 on 2025-08-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0014_accessibility_bathroom_viewfromwindow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='amount_sleeps',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Количество спальных мест'),
        ),
    ]
