# Generated by Django 5.1.5 on 2025-06-22 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0014_dailyprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyprice',
            name='min_stay_days',
            field=models.IntegerField(default=3),
        ),
    ]