# Generated by Django 5.1.5 on 2025-08-10 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0015_object_amount_sleeps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='bathroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.bathroom', verbose_name='Тип ванной комнаты'),
        ),
        migrations.AlterField(
            model_name='object',
            name='view_from_window',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.viewfromwindow', verbose_name='Вид из окна'),
        ),
    ]
