# Generated by Django 5.1.5 on 2025-06-22 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0015_dailyprice_min_stay_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyprice',
            name='price',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
