# Generated by Django 5.1.5 on 2025-08-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0016_alter_object_bathroom_alter_object_view_from_window'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessibility',
            name='accessibility_type',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Специальный возможности'),
        ),
        migrations.AlterField(
            model_name='bathroom',
            name='bathroom_type',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Тип ванной комнаты'),
        ),
        migrations.AlterField(
            model_name='viewfromwindow',
            name='notation_view',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Вид из окна'),
        ),
    ]
