# Generated by Django 5.1.5 on 2025-08-12 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0017_alter_accessibility_accessibility_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessibility',
            options={'verbose_name': 'Спец. возможность', 'verbose_name_plural': 'Специальные возможности'},
        ),
        migrations.AlterModelOptions(
            name='bathroom',
            options={'verbose_name': 'Тип ванной', 'verbose_name_plural': 'Типы ванных комнат'},
        ),
        migrations.AlterModelOptions(
            name='objectaccessibilities',
            options={'verbose_name': 'Спец. возможность для объекта', 'verbose_name_plural': 'Специальные возможности для объектов'},
        ),
        migrations.AlterModelOptions(
            name='viewfromwindow',
            options={'verbose_name': 'Вид из окна', 'verbose_name_plural': 'Виды из окон'},
        ),
        migrations.AlterField(
            model_name='nearmetroobject',
            name='metro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.metro', verbose_name='Метро'),
        ),
        migrations.AlterField(
            model_name='nearmetroobject',
            name='object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.object', verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='object',
            name='accessibility',
            field=models.ManyToManyField(through='objects.ObjectAccessibilities', to='objects.accessibility', verbose_name='Специальный возможности объекта'),
        ),
        migrations.AlterField(
            model_name='object',
            name='amount_sleeps',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Количество спальных мест (количество)'),
        ),
        migrations.AlterField(
            model_name='object',
            name='cost',
            field=models.IntegerField(db_index=True, verbose_name='Стоимость базовая'),
        ),
        migrations.AlterField(
            model_name='object',
            name='inventories',
            field=models.ManyToManyField(through='objects.ObjectInventory', to='objects.inventory', verbose_name='Инвентарь для объекта'),
        ),
        migrations.AlterField(
            model_name='object',
            name='near_metro',
            field=models.ManyToManyField(db_index=True, null=True, through='objects.NearMetroObject', to='objects.metro', verbose_name='Метро у объекта'),
        ),
        migrations.AlterField(
            model_name='object',
            name='services',
            field=models.ManyToManyField(through='objects.ObjectServices', to='objects.service', verbose_name='Услуги для объекта'),
        ),
        migrations.AlterField(
            model_name='object',
            name='sleeps',
            field=models.CharField(max_length=255, null=True, verbose_name='Количество спальных мест (описание)'),
        ),
        migrations.AlterField(
            model_name='objectsmediafile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='objects/images', verbose_name='Файл'),
        ),
    ]
